DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS(ID_AUTHOR BIGINT AUTO_INCREMENT PRIMARY KEY, FULL_NAME VARCHAR(255));

CREATE TABLE GENRES(ID_GENRE BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

CREATE TABLE BOOKS(ID_BOOK BIGINT AUTO_INCREMENT PRIMARY KEY,
                   NAME VARCHAR(255),
                   ID_AUTHOR BIGINT,
                   ID_GENRE  BIGINT,

                   CONSTRAINT FK_AUTHOR FOREIGN KEY (ID_AUTHOR)
                       REFERENCES AUTHORS (ID_AUTHOR)
                       ON DELETE SET NULL,

                   CONSTRAINT FK_GENRE  FOREIGN KEY (ID_GENRE)
                       REFERENCES GENRES  (ID_GENRE)
                       ON DELETE SET NULL
                  );
